dataset:
  target: mortality
  random_state: 1337
  train_size: 0.8
  train_on:
    - dataset: tudd
      fraction: 1.0
    - dataset: mimic
      fraction: 500
  classification: true
  data_cleaner:
    outlier_limits_path: configs/data_limits.json
    missing_threshold_row: 0.5
  scaler_encoder:
    type: none
  imputer:
    imputation_method: none

training:
  - name: tabpfn-3
    task_type: classification
    params:
      random_state: 1337
      predict_batch_size: 512
      fit_mode: "fit_with_cache"
      inference_config: { "SUBSAMPLE_SAMPLES": 15_000 }
    tuning:
      scoring: roc_auc
      cv:
        n_splits: 5
        shuffle: true
        random_state: 1337

plotting:
  enabled: true
  formats:
    - png

mlflow:
  enabled: true
  tracking_uri: sqlite:///mlflow.db
  artifact_location: mlartifacts
  experiment_name: tab
