dataset:
  target: mortality
  random_state: 1337
  train_size: 0.8
  train_on:
    - dataset: tudd
      fraction: 1.0
  data_cleaner:
    outlier_limits_path: configs/data_limits.json
    missing_threshold_row: 0.5
  scaler_encoder:
    type: none
  imputer:
    imputation_method: none
    flag_missing: false
    knn_neighbors: 5

training:
  - name: ebm
    tuning:
      method: optuna
      search_space: good
      scoring: roc_auc
      optuna:
        n_trials: 100
        sampler: tpe
        n_startup_trials: 10
        timeout: null
      cv:
        n_splits: 5
        shuffle: true
        random_state: 1337

mlflow:
  enabled: true
  tracking_uri: sqlite:///mlflow.db
  artifact_location: mlartifacts
  experiment_name: ebm_search_space
