run_number: 1
run_date: 2026-06-17

dataset:
  target: mortality
  random_state: 1337
  train_size: 0.8
  train_on:
    - dataset: mimic
      fraction: 1.0
  classification: true
  data_cleaner:
    outlier_limits_path: configs/data_limits.json
    missing_threshold_row: 0.5
  scaler_encoder: {}
  imputer:
    imputation_method: knn
    flag_missing: false

training:
  models:
    - name: tabpfn-3
      task_type: classification
      params: {}
      hpo: null
    - name: tabicl-2
      task_type: classification
      params: {}
      hpo: null

evaluation:
  metrics:
    - all

plotting:
  enabled: true
  formats:
    - png
