dataset:
  target: mortality
  random_state: 1337
  train_size: 0.8
  train_on:
    - dataset: mimic
      fraction: 1.0
  classification: true
  data_cleaner:
    outlier_limits_path: configs/data_limits.json
    missing_threshold_row: 0.5
  scaler_encoder: {}
  imputer:
    imputation_method: knn
    flag_missing: false

training:
  - name: tabpfn-3
    task_type: classification
    params: {}
    tuning: null
  - name: tabicl-2
    task_type: classification
    params: {}
    tuning: null

plotting:
  enabled: true
  formats:
    - png

mlflow:
  enabled: true
  tracking_uri: sqlite:///mlflow.db
  artifact_location: mlartifacts
  experiment_name: tab
  nested_model_runs: true
  log_models: false
