# experiment:
# external data 100%
# increase local data and review performance

name: external-sample-size
base_config: ../pipeline/baseline.yaml
matrix:
  # keep first for name
  # mimic has 25600, tudd not
  - path: dataset.train_on.0.fraction
    values: [100, 200, 400, 800, 1600, 3200, 6400, 12800, 25600, 1.0]
  - path: dataset.train_on.1.fraction
    values: [1.0]

  # common metadata to change
  # task
  - path: dataset.target
    values: ["mortality"]
  # mlflow name + source, KEEP IN SYNC!
  - path: mlflow.experiment_name
    values: ["sample_size_mimic_mortality"]
  - path: dataset.train_on.0.dataset
    values: ["mimic"]
  - path: dataset.train_on.1.dataset
    values: ["tudd"]

  # repeat runs with other seeds (pretty much dont need to touch)
  - path: random_states
    values:
      - { model_training_seed: 1337, training_sample_seed: 1337, cv_split_seed: 1337 }
    #  - { model_training_seed: 1339, training_sample_seed: 1339, cv_split_seed: 1339 }
    #  - { model_training_seed: 1341, training_sample_seed: 1341, cv_split_seed: 1341 }
    #  - { model_training_seed: 1338, training_sample_seed: 1338, cv_split_seed: 1338 }
    #  - { model_training_seed: 1340, training_sample_seed: 1340, cv_split_seed: 1340 }
